apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: nginx-app-repo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/abhijithvg/my-k8s-repo.git   # Change this to HTTPS
  ref:
    branch: main   # Specify the branch if necessary
