# nginx-app/kustomization.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: nginx-app
  namespace: flux-system
spec:
  interval: 1m
  path: "./nginx-app"  # Adjust path as necessary
  prune: true
  sourceRef:
    kind: GitRepository
    name: nginx-app-repo

